ORACLE_DSN dbi:Oracle:host=172.16.16.159;service_name=orclpdb1;port=1521
ORACLE_USER miguser
ORACLE_PWD password123

PG_DSN dbi:Pg:dbname=migdb;host=127.0.0.1;port=5432
PG_USER postgres
PG_PWD postgres

EXPORT_DIR /home/oracle/ora2pg/export
